package com.sendbird.live.audioliveeventsample.util


const val INTENT_KEY_LIVE_EVENT_ID = "INTENT_KEY_LIVE_EVENT_ID"
const val INTENT_KEY_LIVE_EVENT_COVER_URL = "INTENT_KEY_LIVE_EVENT_COVER_URL"
const val INTENT_KEY_LIVE_EVENT_TOTAL_PARTICIPANTS = "INTENT_KEY_LIVE_EVENT_TOTAL_PARTICIPANTS"
const val INTENT_KEY_LIVE_EVENT_PEAK_PARTICIPANTS = "INTENT_KEY_LIVE_EVENT_PEAK_PARTICIPANTS"
const val INTENT_KEY_LIVE_EVENT_DURATION = "INTENT_KEY_LIVE_EVENT_DURATION"