package com.sendbird.live.videoliveeventsample.util

const val INTENT_KEY_LIVE_EVENT_ID = "INTENT_KEY_LIVE_EVENT_ID"
const val INTENT_KEY_LIVE_EVENT_COVER_URL = "INTENT_KEY_LIVE_EVENT_COVER_URL"
const val INTENT_KEY_LIVE_EVENT_TOTAL_PARTICIPANTS = "INTENT_KEY_LIVE_EVENT_TOTAL_PARTICIPANTS"
const val INTENT_KEY_LIVE_EVENT_PEAK_PARTICIPANTS = "INTENT_KEY_LIVE_EVENT_PEAK_PARTICIPANTS"
const val INTENT_KEY_LIVE_EVENT_DURATION = "INTENT_KEY_LIVE_EVENT_DURATION"
const val INTENT_KEY_LIVE_EVENT_ENDED_AT = "INTENT_KEY_LIVE_EVENT_ENDED_AT"
const val INTENT_KEY_LIVE_EVENT_ENDED_BY = "INTENT_KEY_LIVE_EVENT_ENDED_BY"
const val INTENT_KEY_CREATED_LIVE_EVENT_ID = "INTENT_KEY_CREATED_LIVE_EVENT_ID"
const val INTENT_KEY_SELECTED_HOST_USER_LIST = "INTENT_KEY_SELECTED_HOST_USER_LIST"
